# This is a basic workflow to help you get started with Actions

name: Build and Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: windows-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer, ModuleBuilder -ErrorAction Stop
      - name: Build Module
        shell: pwsh
        run: |
          $Module = Build-Module -SourcePath .\Source\ -passthru
      - name: Lint Built Module
        shell: powershell
        run: |
           Invoke-ScriptAnalyzer -Path .\PSSmartsheet\$Module.Version\PSSmartsheet.psm1 -Settings .\PSScriptAnalyzerSettings.psd1 -Outvariable issues
            $errors   = $issues.Where({$_.Severity -eq 'Error'})
            $warnings = $issues.Where({$_.Severity -eq 'Warning'})
            if ($errors) {
                Write-Error "There were $($errors.Count) errors and $($warnings.Count) warnings total." -ErrorAction Stop
            } else {
                Write-Output "There were $($errors.Count) errors and $($warnings.Count) warnings total."
            }
